# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
r_github_packages:
  - s-fleck/lgr
r_packages:
  - RPostgres
  - RMariaDB
sudo: false
services:
  - postgresql
  - mysql
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install();devtools::test()'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mysql -e 'CREATE DATABASE travis_ci_test;'
